- id: darker
  name: darker
  description: "Black reformatting to Python files only in regions changed since last commit"
  entry: darker
  language: python
  language_version: python3
  require_serial: true
  types: [python]
